apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: pasal

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ghcr-secret
            
      containers:
        - name: backend

          image: ghcr.io/theclouddream/pasal-backend:6f3ee3bab387b0a52bc191d9f6206f3228e0b893

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pasal-config

            - secretRef:
                name: pasal-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 20


