apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: pasal

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: frontend

          image: ghcr.io/theclouddream/pasal-frontend:97a4e8b9b22cdb80308e9504a31b6d6f252b09bc

          ports:
            - containerPort: 80