apiVersion: v1
kind: Secret

metadata:
  name: pasal-secret
  namespace: pasal

type: Opaque

stringData:
  JWT_SECRET_KEY: super_secret_unpredictable_string_for_local_dev

  POSTGRES_DB: pasal_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres