services:
  backend:
    build:
      context: ..
      dockerfile: Docker/backend.Dockerfile

    container_name: pasal-backend

    ports:
      - "8000:8000"

    env_file:
      - ../.env.docker

    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ..
      dockerfile: Docker/frontend.Dockerfile

    container_name: pasal-frontend

    ports:
      - "3000:80"

  postgres:
    image: postgres:17
    container_name: pasal-postgres

    environment:
      POSTGRES_DB: pasal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5436:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pasal-redis

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

networks:
  pasal-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
